### ISSUE TITLE
Datos Públicos y Gobierno Abierto no existe mas

### ISSUE THREAD

**Issue by lbellomo** [j-e-d/nuevosrepos#1]
Las cuentas (ambas: [github](https://github.com/DatosGBA) y [twitter](https://twitter.com/GobAbierto_BA)) de Dirección de Datos Públicos y Gobierno Abierto (Provincia de Buenos Aires) no existen mas.

¿Que se debería hacer? ¿Borrarlas del readme?

**Comment by j-e-d** [comment]
Actualizado, ahora se llama "Dirección Provincial de Evaluación y Gobierno Abierto" y usan otras cuentas. Gracias.
